### ISSUE TITLE
Host Wbijam.pl - nie wyswietla wszystkich anime w pozostalych seriach+nie wyswietla odcinkow w kilku seriach + Rozwiazanie(!)

### ISSUE THREAD

**Issue by grollajt** [huballo/xbmc-huball-repository#10]
Tak jak wyzej 
1.w pozostalych brak np. AIR
2.Brak odcinkow np Naruto Shippuuden, Boruto 
Rozwiazanie 1. nie wiem czy to beda wszystkie ale jest ich napewno wiecej 2.Naprawione:
#11 FIX

**Comment by huballo** [comment]
Ok jutro się tym zajmę. Ogólnie ten host to jest wersja testowa, która leżała już z rok u mnie na komputerze. Jako że proszono mnie o nowe hosty to dodałem go mimo tego, że w zasadzie nie był testowany. Wszelkie poprawki będą miłe widziane.

**Comment by grollajt** [comment]
Jak znajde jakis blad lub rozwiazanie to pomoge

**Comment by huballo** [comment]
Grollajt i misza to jedna osoba?
Dodałem te zmiany ale została wersja stara. Następnym razem mógłbyś zmienić jeszcze wersję w addon.xml trzeba utwozyc nowy addons.xml.md5 i addons.xml i nowy plik zip. Skrypt do tego to addon_xml_generator jest w plikach. Tylko przed utworzeniem nowego zip trzeba wywalić stary żeby nie robiło archiwum z archiwum. Ogarniesz?☺

**Comment by grollajt** [comment]
tak oba nicki naleza do mnie. Raczej ogarne jak nie bede dawal znac
