### ISSUE TITLE
Brak źródeł w anime odcinki

### ISSUE THREAD

**Issue by Misamaru** [huballo/xbmc-huball-repository#12]
Po wejściu w dane anime i wybór odcinka otwier się lista źródeł, ale jest pusta. W każde anime jakie wejdę jest tak samo, okno sie otwiera, ale źródeł nie ma.

**Comment by huballo** [comment]
Zakodowali linki do playerów.

**Comment by Misamaru** [comment]
Czyli nic się nie da zrobić? A może wtedy wtyczka do shindena?

**Comment by huballo** [comment]
Nic takiego nie napisałem przecież.
