### ISSUE TITLE
Kodi 17 - pusty ekran

### ISSUE THREAD

**Issue by newkind** [huballo/xbmc-huball-repository#14]
Hej,

Czy jest jakieś rozwiązanie na pusty ekran po wejściu w Anime-IPTV w Kodi 17+ ?

Dzięki!

**Comment by huballo** [comment]
W jakim hoście?
Nie wszystko działa bo dawno do wtyczki nie zaglądałem. Teraz staram się poprawić Wbijam. Ale łeb mnie boli więc nie wiem ile mi to zajmie. :)

**Comment by newkind** [comment]
W każdym ;) Ogólnie po wejściu do wtyczki od razu masz pusty ekran. Są dźwięki przechodzenia z pozycji na pozycję, ale nic nie widać. Hah! Spoko, głowa ważniejsza ;)

**Comment by huballo** [comment]
Pewnie masz skina Eustary. U mnie na tym skinie też jest pusto. Nie wiem dla czego tak się dzieje. Na innych skinach powinno być ok.

**Comment by newkind** [comment]
Dokładnie. Interesujące jest to, że na Eustary Touch na tablecie wszystko działa poprawnie! Dziwne...

**Comment by huballo** [comment]
Teraz powinno działać. Wywaliłem kilka linijek. Mam nadzieję, że więcej naprawiłem niż popsułem.

**Comment by newkind** [comment]
Działa! :) Dzięki bardzo!
