### ISSUE TITLE
GDrive - urlresolver błąd. 

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#15]
Hej. 
Na wstępie bardzo dziękuję za udostępnienie tej wtyczki, normalnie jedna z moich ulubionych i jedyna właściwa do anime. 
Mam pytanko, lub prośbę czy w wolnej chwili dałoby radę coś zrobić z GDrive. Od jakiegoś czasu nie mogę korzystać z tego źródła, mimo zalogowania. 
Nie jest to palący problem, ale gdyby Ci się nudziło. 
Pozdrawiam i Dziekuje

**Comment by huballo** [comment]
podaj jakieś anime i stronę z której pochodzi bo nie chce mi się szukać. Popatrzę może się coś uda zrobić

**Comment by huballo** [comment]
Siedziałem cały dzień nad tym i chyba zrobiłem. Modziłem i modziłem, a wystarczyło zmienić jeden wyraz w linku do źródła z google. Masakra ;/ W 1.4.5. powinno być oki.
