### ISSUE TITLE
Brak źródeł

### ISSUE THREAD

**Issue by Misamaru** [huballo/xbmc-huball-repository#16]
Witam,
We wtyczce anime odcinki->odcinki anime po wejściu w daną literę jest pusto, w wbijam.pl są anime, ale żaden link źródłowy do odcinka nie działa. W animezone to samo, ale rozumiem, że to dział w budowie więc nie do końca działa

**Comment by bikersoft** [comment]
Może spróbuj zaktualizować wtyczkę. 
U mnie działają, korzystam na android i Osmc Rpi3. 
Oczywiście mam problem ze źródłem gdrive, ale to bardziej niewygodna. 
Aktualna wersja jaka mi pokazuje to 1.4.4
Pozdrawiam.

**Comment by Misamaru** [comment]
Mi tez pokazuje 1.4.4 wersje. Aktualizowałem, nawet na nowo wgrałem po usunięciu wszystkiego.

**Comment by huballo** [comment]
U mnie wszystko jest ok także nie wiem o co biega może to wina skóry? Nie mam pojęcia co może być nie tak.

**Comment by Misamaru** [comment]
Rozumiem.  Skórkę zmieniałem już ( miałem oryginalna od kryptona i starą od gotham bodajże). Nic to nie dało. Nie wiem jak bym mógł Ci opisać/ pokazać dokładniej. Spróbuje dziś bądź jutro na raspberry pi postawić i zobaczę czy jest to samo.

**Comment by undengrand** [comment]
Ja używam kodi v17.3 z skórą Estouchy na telefonie i wszystko jest w porządku lecz gdy włączyłem kodi v16.1 na komputerze to nie było tam żadnych anime.
Sprawdź również czy ci strona anime-odcinki działa bo jeżeli nie to nic się nie pokaże.

**Comment by Misamaru** [comment]
Nie wiem czy to ma coś do rzeczy ale odres strony się zmienił. Występuje teraz pod dwoma adresami a na tym starym jest przekierowanie na nową stronę.

**Comment by bikersoft** [comment]
Nowa wersja już jest 1.4.6 nowa nazwa strony zaktualizowana. 
Co do linków, to proponuję przetestować skórki. 
Od kiedy wersja 17 się pokazała z nowymi skórkami "fabrycznymi" są problemy. 
Ja sobie przełączam na tradycyjną confluence lub korzystam z xonfluence.

**Comment by Misamaru** [comment]
włączyłem dziś kodi, sam zainstalował aktualizację do anime iptv. Zadowolony siadam by sprawdzić czy wszystko działa i... nie działa. Dalej mam tak samo jak miałem, pokazuje mi wersje 1.4.6 wtyczki. Sprawdzane na kilku skórkach (docelowo i tak cały czas używam Confluence). Czy są jeszcze jakieś dodatkowe zależności do tej wtyczki? bo już nie mam pomysłu co do tego dlaczego nie działa poprawnie.

**Comment by LaffinAtcha** [comment]
Hello, I noticed that the Pac12 addon updated yesterday and now it does not launch. Will you be fixing it? The Pac12 addon is still my favorite college sport addon. thank you for your work.
