### ISSUE TITLE
Zmiana strony. Anime-odcinki

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#17]
Hej
Anime-odcinki zdechło. 
Na stronie taki komunikat :
Witamy, od dzisiaj strona znana wam jako anime-odcinki.pl będzie działać jako a-o.ninja Mamy nadzieję, że szybko się przyzwyczaicie do małych zmian :) ~ Pozdrawiamy Administracja

Można prosić o update? 
Pozdrawiam

**Comment by huballo** [comment]
Ci to nie mogą chwile bez zmian posiedzieć. Jutro zobaczę co wymyślili.
