### ISSUE TITLE
Pac-12 Network

### ISSUE THREAD

**Issue by kizzjay1** [huballo/xbmc-huball-repository#18]
The Pac-12 addon was working so well until a few days ago. I just looked it up & saw that you deleted the files recently. Are there any plans of updating this addon so that it works again? I LOVE this addon & it would kill me to lose it right before football season!!! Please please please bring it back!!!

**Comment by huballo** [comment]
This addon will not come back. If you want to use it, simpy install manualny from zip. Latest working version was 1.2.3

**Comment by kizzjay1** [comment]
thank you for getting back to me! I'm so sad that u wont be maintaining this addon any . i tried to grab the plugin for the version u listed above, however, the only version i can find is the one where u deleted the files (1.3.0). can u send me the download link for version 1.2.3 or can you point me into the right direction as to where i can find it? thank you for all your help & thank you for the time you put in when u were supporting this addon!
