### ISSUE TITLE
czy mozna prosic o wznowienie wtyczki ANIME??

### ISSUE THREAD

**Issue by ghost** [huballo/xbmc-huball-repository#20]
jak w temacie, czy mozna prosic o wznowienie wtyczki albo wtyczke do animesub.info z napisami

**Comment by huballo** [comment]
Co jest nie tak z tą wtyczką?  Mi działa. Więcej szczegółów proszę.

**Comment by ghost** [comment]
przepraszam, zle sie wyrazilem, repo wygladalo na opuszczone (czas uplyniety od wstawienia pliku na prawo w repo), brak pewnych kluczowych funkcji w dzialach wskazywal na niedokonczona/porzucona prace, czy mozna podrzucic pare pomyslow/ stronek ktore warto by bylo dolaczyc jako wklad od fana anime??, bardzo zalezy mi na porzadnej wtyczce do anime bo takowej BRAK z ramic srednio sie idzie skomunikowac i cokolwiek zasugerowac wiec fajnie by bylo moc sie dogadac i cos pomoc od strony uzytkownika

**Comment by ghost** [comment]
poza tym chcialem sie zapytac kulturlanie, czy moge zamiescic twoje repo w moim DARMOWYM (i tak zawsze pozostanie) buildzie

**Comment by huballo** [comment]
Co to za bulid?

**Comment by ghost** [comment]
moja przygoda z kodi zaczela sie 2 miesiace temu (okolo),  jest sporo angielskich buildow, ale one mi nie odpowiadaja (wiec z  tego powodu zrobilem wlasny), poza tym nie ma kontentu polskiego poza scraperami z polskich zrodel po przestawieniu jezyka, alternatywa to ramic, ale on walczy z buildami bo paru januszy biznesu chcialo na nim zarobic, ja nie mam wiedzy o pytonku zeby samemu robic wtyczki, ale inteligencji wystarczy mi na zrobienie buildu https://www.youtube.com/watch?v=9CfOz16thCE
grzecznie inormuje, ze twoje repo znajduje sie teraz w moim DARMOWYM buildzie, jestem fanem anime i dlatego z przyjemnoscia bede czekal na to jak rozwijac sie bedzie twoje repo

PS:( aktualnie mamy na polskiej scenie kodi z tego co wiem buildy ALien, kodiultimate, MultimediMaster nie jest juz rozwijany z tego co wiem- PLATNE(janusze biznesu) i darmowe QWER, CHERRY,M-BOX, ), o innych buildach nie wiem

jak cos zapraszam do mnie na moje wypociny githubowe

**Comment by ghost** [comment]
lista addonow anime(nie wszystkie sprawdzone) : 
Funimation NOW -platna
Crunchyroll -platna
Wakanim
Nie oficjalne
9anime
animego
Daisuki - zamknieta
Masterami
Anime Brasil
Anime on Demand - niemiecka
wtyczki napisow do QUASAR
kiss anime
kiss asian
Ares Anime
AnimeRam
Anime44
AnimeFTW.tv- zamknieta
AnimeHere
AnimeGo
9Anime
SOGGYSANWITCH
WATCH CARTOON ONLINE 

osobiscie najlepsze wg mnie to 
Masterami
9anime
SOGGYSANWITCH
Anime on Demand

niestety ciezko z dopasowywaniem napisow, a zrodla z polskimi napisami wtopionymi to tez ciezko
dlatego tak czekam na twoje repo:D
podzial i ekspozycja poszczegolnych anime jest kluczowa z mojego punktu widzenia we wtyczce...
podzial na listy wg alfabetu dobra sprawa ale brakuje pare opcji wg mnie,
wystarczylo by zeby dodac opcje wylistowania calosci zbioru anime z danej strony podzielone na strony po 50 i dzial z najnowszymi odcinkami pierwsze 20 z danej strony i przycisk szukaj, a jakby doszedl podzial na podgatunki oraz ulubione  to wielo osob powiesi sobie znaczek huballo jako plakat na scianie z radosci:D
