### ISSUE TITLE
Problem z wtyczką Anime-IPTV

### ISSUE THREAD

**Issue by ZochoK** [huballo/xbmc-huball-repository#21]
Witam,
Po postawieniu na czysto kodiego 17.06, przy każdej próbie odpalenia filmu z serwisu anime-online.pl wywala mi błąd pt. "Nie udało się niestety :(BUUU". Problem pojawia się niezależnie od wybrania hostingu. Jest na to jakieś lekarstwo? (Kilka miesięcy temu na wersji 17.3 wszystko działało bez problemu. Testowane na Androidzie i Windowsie)

**Comment by pcpl2** [comment]
Z tego co ja testowałem to działa hosting vidlox, żaden inny mi nie działał.

**Comment by huballo** [comment]
Działa VIDFile, openload, cda.... także na pewno nie jest tak jak mówicie. ZochoK podaj jakiś przykład proszę to zobaczę o co chodzi.

**Comment by ZochoK** [comment]
Powiedz co mam ci sprawdzić. Niezależnie jaki serial chcę obejrzeć z Anime-online.pl, po wybraniu któregoś z hostingów (VIDfile, Openload itd.) zawsze jest ten sam efekt - Od razu komunikat  "Nie udało się niestety :(BUUU" 
Wersja wtyczki 1.6.1
Wersja Kodi 17.6 Git:20171114-a9a7a20

**Comment by huballo** [comment]
Zobacz na początek jaką masz wersję urlresolver, ja mam 4.08.08

**Comment by ZochoK** [comment]
Zainstalowałem wersje 4.0.9 a potem 4.0.15 i zaczęły działać linki z hostu openload. Cała reszta dalej nie funkcjonuje.

**Comment by ZochoK** [comment]
Może pomogą logi kodiego https://pastebin.com/xLD7Lwij

**Comment by huballo** [comment]
Jutro zainstauje wszytko na czysto i zobaczę. Najlepsze jest ze u mnie w robocie wszystko działa tak jak pisałem. Za to w domu już nie. Tylko jak tu teraz znaleźć przyczynę tego. To mi dales robote 😂

**Comment by ZochoK** [comment]
W takim razie życzę powodzenia i czekam na na jakieś informacje. Odwaliłeś kawał dobrej roboty, a ta wtyczka to "must have" w moim domu ;)

**Comment by ghost** [comment]
a moze kwesia parowania openload vidup i vshare?

**Comment by huballo** [comment]
Dotarłem w końcu do roboty. Trochę mi to zajęło. 
Nadal wam to nie działa? Sprawdzam na kompie i na telefonie i większość mi działa.

**Comment by ghost** [comment]
kiedy mozna by sie spodziewac jakich dzialow ostatnio dodane albo cos, zeby latwiej bylo ogladac nowosci,  by nie szukac najnowszych odcinkow ktore wchodza w liscie a-z, da sie cos takeigo latwo zrobic?

**Comment by huballo** [comment]
Nie musisz szukać nowości w liście a-z. Możesz dodać anime do ulubionych.
Żeby pokazywało nowości to trzeba dodać do każdego hosta nowy dział z nowościami. A jeden dla wszystkich hostów nie wiem czy się da zrobić.

**Comment by ghost** [comment]
@a nie da sie zrobic tego na zasadzie sledzenia dzialu ktorejs ze stron, a potem ewentualnego scrapowania po nazwie np z https://myanimelist.net/watch/episode @(jestem w stanie wyszukac jeszcze pare linkow na przyklady) jako baza do tworzenia listy nowych odcinkow, tak zeby lista tworzyla sie na bazietego dzialu w servisie a potem dopiero po kliknieciu zeby scrapowalo linki przynalezne do tej nazwy z pozostalyuch stron ktore sa we wtyczce, i wylistowane ... taka przejsciowka poprostu, to wazne z punktu widzenie uzytkownika by moc poza dzialem a-z, ulubionymi miec jeszcze mozliwosc zobaczenia co nowego wyszlo i o ile to wykonalne dla ciebie podzialu na gatunki, jesli nie da sie tego zrobic statycznie bo za czaso chlonne to moze dynamicznie w oparciu o tagi-dane wyciagniete z jakiegos popularnego servisu, jelsi udalo by ci sie to wykonac to byly pierwszy POLSKI w pelni funkcjonalny addon anime,  to nie kwestia mojego gderania, ale kwestia ergonomi, nawigacji menu oraz funkcjonalnosci, tego poprostu brakuje do wygodnego kozystania (slyszales o zasadzie 5ciu klikniec w tworzeniu interfejsu?)

**Comment by huballo** [comment]
Da się tylko trzeba napisać nową wtyczkę a do tego to musisz zatrudnić kogoś innego. Przydałoby się żeby też wszystkie strony miały takie same nazwy anime bo wystarczy jedna spacja i dupa. Nie wszystkie strony też oferują wyszukiwanie. Ale jak już wspomniałem ja tego pisał nie będę bo ani czasu nie mam ani umiejętności. Od 2 lat nie obejrzałem żadnego anime ani filmu bo nie mam nawet jednej chwili wolnej w ciągu dnia. Zapytaj Ramica może on coś takiego napisze. On się na Pythonie zna.

**Comment by ghost** [comment]
ramic jest zabardzo zarozumialy, poza tym zamkneli mu repo za zabezpieczenia przeciw buildom ktore nosily znamiona zlosliwego oprogramowania (czyscilo ludziom profile cale w c:users)
