### ISSUE TITLE
KOCHAM CIE CHŁOPIE ZA TE SUBY OD ANIMESUB:****

### ISSUE THREAD

**Issue by ghost** [huballo/xbmc-huball-repository#23]
Jak w temacie, JESTEŚ WIELKI ide testować:D

**Comment by ghost** [comment]
jest szukanie manualne...super, jest tez automatyczne... zadko bedzie trafne ale tez super, ale czemu nie chce dopasowac napisow wg ustawien kodi, nie moge zmienic koloru i wielkosci liter, moze to wina formatu napisow...? i którym klawiszem wlanczalo sie przesuniecie napisow:D 

po testach to napewno kwestia formatu napisow, czyli ktorys format jest problemem pewnie ass albo srt, czy dalo by sie wbudowac jakis konverter??

**Comment by huballo** [comment]
Pewnie format ass, w nim jest większość subów do anime. Napisz na oficjalnym forum kodi może dodadzą lepsze wsparcie do tych napisów. Tylko nie wklejaj logów swoich bo ci post wywalą za posiadanie wtyczek niezgodnych z regulaminem.
