### ISSUE TITLE
Brakujące anime

### ISSUE THREAD

**Issue by ghost** [huballo/xbmc-huball-repository#24]
Boruto next generation nie ma w anime-centrum.pl, a w anime-odcinki.pl jest  5 odcinkow,

**Comment by huballo** [comment]
Ale to chyba informacja dla twórców tych stron. Ja nie mam z nimi nic wspólnego. Sprawdź na tych stronach najpierw ile mają i czy w ogóle mają jakieś odcinki.
Na Senpai mają więcej.
