### ISSUE TITLE
Brak playerow 

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#25]
Hej
Od kilku dni Anime-odcinki nie generuje żadnych playerow po wybraniu. Tylko czarne okienko.
Stalo się tak z dnia na dzień, nie było żadnej aktualizacji. Testowałem na Android i Rpi OSMC.
Co ciekawe na odcinki z wbijam działają bez zarzutu.
Do się coś z tym zrobić?
Dzięki i pozdrawiam.

**Comment by huballo** [comment]
Poszedł fix. Jak nadal coś nie będzie działać daj znać.

**Comment by bikersoft** [comment]
Dzięki to było szybkie.
A tak odnośnie pozostałych, anime-centrum brak tytułów.
AnimezonePL również brak playerow.
Ale tam rzadko zaglądam, głównie korzystam z anime odcinki. 
StrefaDB też coś kuleje. 
Dopiero jak padło zacząłem szukać na pozostałych. 
Ale odnośnie Anime odcinki wszystko działa. 
Dziękuję i Pozdrawiam

**Comment by huballo** [comment]
Nikt nie korzysta to i nie wiem co poprawiać trzeba. Przyjrzę się temu.
centrum i zone naprawione- testować
Co jest nie tak w StrefaDB?

**Comment by bikersoft** [comment]
Hej
StrefaDB do końca nie jestem pewien, czy to wtyczka czy urlresolver.
Jak wywołam odcinek na przykład z napisami, pokazuje okienko żeby openload sparowac co robię. Następnie zamieli i wywala błąd. 
Update: To jednak urlresolver, linki z openload zdechly.
