### ISSUE TITLE
asnimesub.info

### ISSUE THREAD

**Issue by ghost** [huballo/xbmc-huball-repository#26]
Nie wiem czy pamietasz jak mowilem o problemach z niektorymi napisami w wyswietlaniu... http://kodi.lanik.org/cleansubs.html# obczaj to, moze pomoze cos dopisac do wtyczki, zapostowal to osobnik na KWP i obiecalem Ci to pokazac bo moze sie przydac

**Comment by XeonFX** [comment]
Możesz opisać dokładnie o co chodzi?
