### ISSUE TITLE
wbijam.pl

### ISSUE THREAD

**Issue by Ellyson13** [huballo/xbmc-huball-repository#27]
siemka poznikaly playery na wbijam.pl moglbys spojrzeć na to ?

**Comment by huballo** [comment]
Poszedł fix. Sprawdź.
Z tego co widzę akurat w tym hoście jest dużo do poprawiania przy listowaniu odcinków. Szkoda, że nikt tego nie zgłasza :(

**Comment by Ellyson13** [comment]
działa superancko :D :D dzięki wielkie :D jak coś znajdę jeszcze to będę zgłaszał :D
