### ISSUE TITLE
Brak list tytułów. 

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#28]
Witam
Anime-odcinki i Anime-centrum nie wyświetla tytułów. Rzuć okiem w wolnej chwili.
Pozdrawiam.

**Comment by huballo** [comment]
Z tego co widzę Anime-odcinki się wyświetlają.
Anime-centrum wyleci bo trzeba płacić za oglądanie. Chyba, że wykupujesz u nich te punkty to daj znać.
Strefadb na razie nie działa. Brak czasu
Aniem-zone też do poprawienia. Brak czasu

**Comment by huballo** [comment]
Anime-Zone też wyleci. badziew

**Comment by bikersoft** [comment]
Dzięki. Zauważyłem że anime - odcinki zaczęły działać, ale nie zdążyłem zgłosić. Też z czasem u mnie nie ciekawie.
Pozostałe zaglądam tylko jako alternatywa, jak wbijam albo odcinki padną.
Pozdrawiam
