### ISSUE TITLE
 1.1.4 nie aktualizuje statusu odcinkow

### ISSUE THREAD

**Issue by Misamaru** [huballo/xbmc-huball-repository#3]
hej,
wtyczka działa jak wersja 1.1.2 zanim przestała pokazywać listę anime. Teraz jest taki problem, że anime jest odcinki są, ale nie aktualizuje ich. Nie dodaje nowych odcinków do serii, nie dodaje nowych serii anime. Próbowalem podmienić pliki w w zipie (te, ktore widziałem, że są świeższe od samej wtyczki), ale nic to nie dało, a nawet pogorszyło działanie wtyczki.

**Comment by huballo** [comment]
heja
Mały szok, że ktoś używa tej wtyczki oprócz mnie :)
Po pierwsze wtyczka przestała działać bo zmienili wygląd strony, a co za tym idzie i jej kod.
Po drugie wydaje mi się, że po ostatnich poprawkach jakoś tam działa. Może wywal ją i zainstaluj ponownie.
Nie mam bardzo czasu się tym zajmować od roku praktycznie z niej nie korzystałem. Podaj jakieś konkretne przykłady to w wolnej chwili spróbuje poprawić jeśli coś nie działa.
Pozdrawiam

**Comment by Misamaru** [comment]
1.1.2 działała ok, ale mówisz, że zmienili wygląd i się popsuło. Od tego momentu nie wyświetlało mi w ogóle ani listy anime ani odcinków. Jak wgrałem wersję 1.1.4 to pojawiła się lista anime, ale stan odcinków jest taki, że na stronie jest zakończone, a we wtyczce nie np servamp zakończył się bodajże we wrześniu i wszystkie odcinki są dostępne, a we wtyczce jest przedostatni odcinek i tyle.  Widzialem na githubie, że sama wtyczka ma inna datę aktualizacji od tego niektorych plików (bodajże .list jakieś), więc zacząłem podmieniać i edytować, ale za każdym razem nie działało :(. poza tym nowe tytuły anime co pojawiły sie w sezonie jesień/zima nie są dostępne z wtyczki. Jestem z Bydgoszczy akurat i znam parę osób co korzysta z tej wtyczki, a sam nie raz innym polecałem bo bardzo dobrze działała :). Pisałem do ludzi z anime odcinki i do shindena czy oni też zarządzali tą wtyczką, ale się okazuje, że nikt nic nie wie wtyczka jest i nie działa. tyle. 

Dzięki za odpowiedź i pozdrawiam

**Comment by huballo** [comment]
Servamp na stronie widzę 11 odcinków i tyle też mi pokazuje się w kodi. Spróbuj odinstalować wtyczkę potem moje repo. I od początku zainstaluj repo i znowu wtyczkę. Zobaczymy czy to coś da. Jak nadal nie będzie listowac nowych anime to napisz jakie pomodze coś po świętach.

**Comment by Misamaru** [comment]
ok po reinstalacji, tak jak mówiłeś, zaczęło wszystko działać :). odcinki się wczytują jest ich taka sama ilość jak na stronie. Jednego anime nie widzę, al to dlatego, że nie ma go w zakresie. we wtyczce jest zakres od a do z i od 1 do 5 bez 4, a anime nazywa się 91days. takto wszystko wygląda i działa dobrze. Pytanie: istnieje szansa by inne serwisy anime zostały podczepione do wtyczki taki jak np shinden? zaoferowałbym swoją pomoc do tego, ale nie te umiejętności niestety... ;(
