### ISSUE TITLE
Napisy

### ISSUE THREAD

**Issue by wombad** [huballo/xbmc-huball-repository#31]
Nie wiem czy tylko u mnie, ale wtyczka nie wyszukuje napisów. Jakby ktos mogl sprawdzic to prosze o info.

**Comment by huballo** [comment]
W ogóle czy tylko ręczne wpisywanie?
Przywróciłem starą wersję. Sprawdź

**Comment by wombad** [comment]
Ręczne nie działało. A co do szukania "automatycznego" to nie wiem bo nazwy odcinków rzadko pokrywają się z nazwą anime. Stara wersja działa.

**Comment by XeonFX** [comment]
Podaj przykładową nazwę odcinka dla którego jest problem z automatycznym wyszukiwaniem.

**Comment by wombad** [comment]
Ja ogladam anime online i czasami nie ma w nich polskich napisow. A nazwy odcinkow sa typu 568fz46gdjy574ghjf47gbj.mp4 wiec nie znajdzie mi samo xd

**Comment by XeonFX** [comment]
Czy przypadkiem używasz np. jDownloader do pobierania ze stron co udostępniają anime online?

**Comment by leonzawodowiec12** [comment]
Anime-odcinki,  wbijam, senpai tylko te strony działają prawidłowo w wtyczce możesz zerknąć na pozostałe np. Dragon Ball nie widać linków
