### ISSUE TITLE
A-o.ninja - Anime-odcinki zmiana domeny

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#33]
Hej Anime-odcinki przestało działać. 
Znalazłem na ich Facebooku że a-o.ninja wróciło na domenę anime-odcinki.pl
Mógłbyś zaktualizować wtyczkę proszę.
Pozdrawiam.

**Comment by huballo** [comment]
Ciekawe ile jeszcze razy zmienią tą domenę.
Poszła aktualizacja. Sprawdź.

**Comment by bikersoft** [comment]
Działa, jesteś Wielki.
Dzięki i pozdrawiam
