### ISSUE TITLE
Wbijam - brak tytułów. 

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#34]
Hej witam
Na wbijam	 "Polecane serie" nie listuje odcinków.
Jakbyś mógł rzucić okiem i użyć swojej magii.
Pozdrawiam

**Comment by huballo** [comment]
Sprawdź proszę teraz.

**Comment by bikersoft** [comment]
Hej
Sorki ze dopiero teraz odp.
W pracy utknąłem I nie było jak sprawdzić.
Zmieniło się menu, znikły gry i coś tam. 
Niestety, ale "Polecane serie anime" dalej nie wyświetla tytułów, a tak akurat nowości są.
Pozdrawiam

**Comment by huballo** [comment]
Sprawdź teraz i daj znać czy działa.

**Comment by bikersoft** [comment]
Witam
Działa pięknie.
Dziekujemy
