### ISSUE TITLE
Wbijam ponowny problem. 

### ISSUE THREAD

**Issue by bikersoft** [huballo/xbmc-huball-repository#35]
Witam
Wbijam znowu nie listuje "polecanych odcinków"
3 dni działało bez problemu.

**Comment by huballo** [comment]
Zrobione :) Sprawdź

**Comment by bikersoft** [comment]
Dziekuje
Pozdrawiam

**Comment by Ellyson13** [comment]
Na wbijam wogule mi nie pokazuje nic na liscir natomiast jak wejde w jakas kategorie po ulubionych to wchodzi ?

**Comment by bikersoft** [comment]
Proponuję otworzyć nowy wątek, ten zamknięty od 4dni.
Nie jestem pewny czy dotrze do autora. Pozdrawiam
