### ISSUE TITLE
Wbijam.pl

### ISSUE THREAD

**Issue by Ellyson13** [huballo/xbmc-huball-repository#36]
Siemka nie pokazuje mi nic po wejsciu na wbijam.pl. Natomiast jak wejde w poszczegolne rzeczy przez ulubione to tam listuje normalnie

**Comment by huballo** [comment]
Zrobione, może wytrzyma dłużej :D sprawdź

**Comment by Ellyson13** [comment]
Działa pięknie :D :+1:
