### ISSUE TITLE
Problem z podkategoriami w wbijam.pl

### ISSUE THREAD

**Issue by Ellyson13** [huballo/xbmc-huball-repository#37]
Siemka teraz jak wchodze w wbijam.pl na kazdej z trzech kategorii nic nie listuje dalej ... :(

**Comment by grollajt** [comment]
Wystarczy w pliku hostwbijam.py od lini 65-79 zamienic na i powinno wszystko grac:
`    if 'Polecane serie anime' in url:
        data1 = '<div class="pmenu_naglowek_a">Polecane serie anime</div>'
        data2 = '//inne.wbijam.pl/">Pozostałe serie</a>'
        link = ''
        mode = 'Browse_Episodeswijam'
    elif 'Lżejsze klimaty' in url:
        data1 = '<div class="pmenu_naglowek_b">Lżejsze klimaty</div>'
        data2 = '>Gry MMO anime'
        link = 'http://www.inne.wbijam.pl/'
        mode = 'Browse_Episodeswijaminne'
    elif 'Akcja' in url:
        data1 = '<div class="pmenu_naglowek_b">Akcja</div>'
        data2 = '<div class="pmenu_naglowek_b">Lżejsze klimaty</div>'
        link = 'http://www.inne.wbijam.pl/'
        mode = 'Browse_Episodeswijaminne'`

**Comment by Ellyson13** [comment]
Super Działa czyli tylko zamienic blue na a i red na b w pmenu_naglowek i wszystko cacy Ekstra zamykam 👍
