### ISSUE TITLE
wbijam.pl

### ISSUE THREAD

**Issue by Ellyson13** [huballo/xbmc-huball-repository#39]
Znowu nie listuje po wejściu na wbijam.pl

**Comment by grollajt** [comment]
Wystarczy zmienic w hostwbijam.py linia ~37 
` html = GetDataBeetwenMarkers(html, 'Menu Główne</div>', '<script type=', False)[1]`
z "Główne" na "główne"
i powinno działać.

**Comment by Ellyson13** [comment]
Extra działa :D zamykam
