### ISSUE TITLE
Prośba dodania serwisów

### ISSUE THREAD

**Issue by eko5** [huballo/xbmc-huball-repository#4]
Czy jest możliwość dodania serwów do wtyczki :)

http://www.animezone.pl/
http://shinden.pl
http://www.dansetsu.pl

**Comment by huballo** [comment]
Co jest na tych stronach wartego uwagi, a czego nie ma na anime online?
Dansetsu nic mi się nie otwiera.
Animezone też za ciekawie nie wygląda.
Shniden kiedyś był dodany, ale że nic na nim nie oglądałem wyleciał jak zmienili kod strony. Do tego dzisiaj się nawet otworzyć nie chce.

**Comment by Misamaru** [comment]
zawsze jakaś alternatywa do anime, które nie jest dostępne na anime odcinki :)

**Comment by eko5** [comment]
Pytasz czego nie ma na anime online np . 12 kingdoms / Juuni Kokki tytuł starszy ale lubie czasem powracać do niego . W sieci znalazłem skrypt do animezone może byś przejrzał i jak się nadaje dodał do wtyczki :) https://drive.google.com/open?id=0B-88N7MdB3tgTUR4Wk9lLWhrZ3M

**Comment by huballo** [comment]
Skąd pochodzi ten plik?

**Comment by eko5** [comment]
https://github.com/ramicspa/kodi/tree/master/zips/plugin.video.anime.pl  folder plugin.video.anime.pl-1.3.zip

**Comment by huballo** [comment]
Wydaje mi się, że ta wtyczka ciągnie wszystko ze strony on-anime. Ten kod od animezone chyba nie za bardzo coś działa. Chociaż mogę się mylić. Ja w sprawach programowania to lalik w zasadzie  jestem. Posiedzę nad tym jeszcze po weekendzie.

**Comment by huballo** [comment]
Ja tej strony nie ogarnę. Nie potrafię jej zmusić do wyplucia adresu odcinka.
