### ISSUE TITLE
Wbijam.pl playery nie dzialaja i dziwne kategorie

### ISSUE THREAD

**Issue by Ellyson13** [huballo/xbmc-huball-repository#41]
Żaden player nie działa na wbijam cokolwiek wybiore pisze ups cos poszlo nie tak a na domiar złego w pierwszym wyborze tam gdzie jest akcja , lżejsze ... Pokazały sie jeszcze jakies dziwne kategorie :/

**Comment by huballo** [comment]
Sprawdź teraz.

**Comment by Ellyson13** [comment]
wszystko działa :D zamykam 👍
